sampleservice:
  build: .
  links:
   - sampleDb
   - queue
  volumes_from:
   - logging
logging:
  image: debian:wheezy
  volumes:
   - /var/log/rook:/var/log/rook
sampledatastore:
  image: debian:wheezy
  volumes:
   - /var/data/rook:/data/db
sampledb:
  image: mongo
  volumes_from:
   - sampleDatastore
queuedatastore:
  image: debian:wheezy
  volumes: 
   - /var/queue:/var/lib/rabbitmq/mnesia
queue:
  image: rabbitmq:management
  ports:
   - "8080:15672"
   - "5672:5672"
  volumes_from:
   - queueDatastore